# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0004_delete_chatusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('chat_uuid', models.CharField(max_length=500)),
                ('channel', models.CharField(max_length=500)),
            ],
        ),
    ]
