# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0007_auto_20171221_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
