# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0010_auto_20171221_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategories',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
    ]
