# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0012_cartitems_usercart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='usercart',
            options={'verbose_name': 'User Cart', 'verbose_name_plural': 'user Carts'},
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='title',
            field=models.CharField(choices=[('Risk Management', 'Risk Management'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Project Management Fundamentals', 'Project Management Fundamentals'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Networking for Success', 'Networking for Success'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Self Leadership', 'Self Leadership'), ('Business Process Management', 'Business Process Management'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Building Better Teams', 'Building Better Teams'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One')], max_length=255),
        ),
    ]
