# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0013_auto_20171223_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='cart_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
