# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0014_cartitems_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
