# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0015_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('current_rate', models.DecimalField(decimal_places=9, max_digits=9)),
            ],
        ),
    ]
