# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0016_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='current_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
