# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0017_auto_20171225_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_payment_id', models.IntegerField()),
                ('payment_status', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=9)),
                ('name_first', models.CharField(max_length=255)),
                ('name_last', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_payment_id', models.CharField(max_length=101)),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
