# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0018_orders_usercourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pf_payment_id',
            field=models.CharField(max_length=255),
        ),
    ]
