# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0019_auto_20171225_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pf_payment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='pf_payment_id',
            field=models.IntegerField(),
        ),
    ]
