# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0021_testsig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSig',
        ),
    ]
