# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0022_delete_testsig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=255)),
            ],
        ),
    ]
