# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0024_testsig_from_where'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSig',
        ),
    ]
