# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0025_delete_testsig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('expiry', models.DateField()),
            ],
        ),
    ]
