# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0026_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='expiry',
            field=models.CharField(max_length=255),
        ),
    ]
