# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0028_auto_20171227_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchers',
            options={'verbose_name': 'Course Voucher', 'verbose_name_plural': 'Course Vouchers'},
        ),
    ]
