# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0029_auto_20171227_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='voucher',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourses',
            name='voucher_expiry_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
