# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0030_auto_20171227_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
    ]
