# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0032_voucherstotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Risk Management', 'Risk Management'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Project Management Fundamentals', 'Project Management Fundamentals'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Networking for Success', 'Networking for Success'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Self Leadership', 'Self Leadership'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Building Better Teams', 'Building Better Teams'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One')], max_length=500)),
                ('course_id', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Course Vouchers 2',
                'verbose_name': 'Course Voucher 2',
            },
        ),
        migrations.CreateModel(
            name='CourseVouchersTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Risk Management', 'Risk Management'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Project Management Fundamentals', 'Project Management Fundamentals'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Networking for Success', 'Networking for Success'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Self Leadership', 'Self Leadership'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Building Better Teams', 'Building Better Teams'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One')], max_length=255)),
                ('course_id', models.IntegerField()),
                ('expiry', models.CharField(max_length=255)),
                ('total_vouchers', models.IntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Voucher Totals 2',
                'verbose_name': 'Voucher Total 2',
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='paiduser',
            options={'verbose_name': 'Paid User', 'verbose_name_plural': 'Paid users'},
        ),
        migrations.AlterModelOptions(
            name='usercourses',
            options={'verbose_name': 'User Course', 'verbose_name_plural': 'User Courses'},
        ),
        migrations.AlterModelOptions(
            name='voucherstotal',
            options={'verbose_name': 'Voucher Total', 'verbose_name_plural': 'Voucher Totals'},
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='title',
            field=models.CharField(choices=[('Risk Management', 'Risk Management'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Project Management Fundamentals', 'Project Management Fundamentals'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Networking for Success', 'Networking for Success'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Self Leadership', 'Self Leadership'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Building Better Teams', 'Building Better Teams'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='course',
            field=models.CharField(choices=[('Risk Management', 'Risk Management'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Project Management Fundamentals', 'Project Management Fundamentals'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Networking for Success', 'Networking for Success'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Self Leadership', 'Self Leadership'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Building Better Teams', 'Building Better Teams'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One')], max_length=500),
        ),
        migrations.AlterField(
            model_name='voucherstotal',
            name='course',
            field=models.CharField(choices=[('Risk Management', 'Risk Management'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Project Management Fundamentals', 'Project Management Fundamentals'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Networking for Success', 'Networking for Success'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Self Leadership', 'Self Leadership'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Building Better Teams', 'Building Better Teams'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One')], max_length=255),
        ),
    ]
