# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0034_remove_coursevoucherstotal_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vouchers',
        ),
        migrations.DeleteModel(
            name='VouchersTotal',
        ),
        migrations.AlterModelOptions(
            name='coursevouchers',
            options={'verbose_name': 'Course Voucher', 'verbose_name_plural': 'Course Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='coursevoucherstotal',
            options={'verbose_name': 'Voucher Total', 'verbose_name_plural': 'Voucher Totals'},
        ),
    ]
