# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0035_auto_20171228_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
