# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0036_orders_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
