# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0039_auto_20171229_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiduser',
            name='portal_id',
            field=models.IntegerField(default=85229),
            preserve_default=False,
        ),
    ]
