# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0040_paiduser_portal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtalPasswordResets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('portal_user_id', models.IntegerField()),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portal Password Reset',
                'verbose_name_plural': 'Portal Password Resets',
            },
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='title',
            field=models.CharField(choices=[('Project Management Fundamentals', 'Project Management Fundamentals'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Microsoft Office 365 Part 1', 'Microsoft Office 365 Part 1'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One'), ('Networking for Success', 'Networking for Success'), ('Self Leadership', 'Self Leadership'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building Better Teams', 'Building Better Teams'), ('Risk Management', 'Risk Management')], max_length=255),
        ),
        migrations.AlterField(
            model_name='coursevouchers',
            name='course',
            field=models.CharField(choices=[('Project Management Fundamentals', 'Project Management Fundamentals'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Microsoft Office 365 Part 1', 'Microsoft Office 365 Part 1'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One'), ('Networking for Success', 'Networking for Success'), ('Self Leadership', 'Self Leadership'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building Better Teams', 'Building Better Teams'), ('Risk Management', 'Risk Management')], max_length=500),
        ),
        migrations.AlterField(
            model_name='coursevoucherstotal',
            name='course',
            field=models.CharField(choices=[('Project Management Fundamentals', 'Project Management Fundamentals'), ('Project Management Training: Understanding Project Management', 'Project Management Training: Understanding Project Management'), ('Leadership Skills for Supervisors: Communication, Coaching and Conflict', 'Leadership Skills for Supervisors: Communication, Coaching and Conflict'), ('Team Building: Developing High Performance Teams', 'Team Building: Developing High Performance Teams'), ('Effective Planning And Scheduling', 'Effective Planning And Scheduling'), ('Customer Service: Critical Elements of Customer Service', 'Customer Service: Critical Elements of Customer Service'), ('Six Sigma: Entering the Dojo', 'Six Sigma: Entering the Dojo'), ('Strategic Planning', 'Strategic Planning'), ('Building Relationships for Success in Sales', 'Building Relationships for Success in Sales'), ('Telemarketing: Using the Telephone as a Sales Tool', 'Telemarketing: Using the Telephone as a Sales Tool'), ('Microsoft Office 365 Part 1', 'Microsoft Office 365 Part 1'), ('Microsoft Project 2016 Part One', 'Microsoft Project 2016 Part One'), ('Networking for Success', 'Networking for Success'), ('Self Leadership', 'Self Leadership'), ('Business Leadership: Becoming Management Material', 'Business Leadership: Becoming Management Material'), ('Building an Online Business', 'Building an Online Business'), ('Change Management: Change and How to Deal With It', 'Change Management: Change and How to Deal With It'), ('Managing Across Cultures', 'Managing Across Cultures'), ('Prospecting for Leads like a Pro', 'Prospecting for Leads like a Pro'), ('Selling Smarter', 'Selling Smarter'), ('Entrepreneurship 101', 'Entrepreneurship 101'), ('Writing A Business Plan', 'Writing A Business Plan'), ('Building Better Teams', 'Building Better Teams'), ('Risk Management', 'Risk Management')], max_length=255),
        ),
    ]
