# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0041_auto_20180104_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursevouchers',
            name='course',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coursevoucherstotal',
            name='course',
            field=models.CharField(max_length=255),
        ),
    ]
