# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0043_orders_amount_gross_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevoucherstotal',
            name='course_img',
            field=models.ImageField(max_length=255, null=True, upload_to='images/course_images'),
        ),
    ]
