# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0044_coursevoucherstotal_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevoucherstotal',
            name='course_img',
        ),
    ]
