# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0045_remove_coursevoucherstotal_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('course_image', models.ImageField(max_length=255, null=True, upload_to='images/course_images/book')),
                ('course_image_main', models.ImageField(max_length=255, null=True, upload_to='images/course_images/main')),
                ('price', models.DecimalField(decimal_places=2, default=180.0, max_digits=6)),
            ],
        ),
    ]
