# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0046_courseimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimages',
            options={'verbose_name': 'Course image', 'verbose_name_plural': 'Course images'},
        ),
        migrations.AlterField(
            model_name='courseimages',
            name='course_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/course_images/book'),
        ),
        migrations.AlterField(
            model_name='courseimages',
            name='course_image_main',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/course_images/main'),
        ),
    ]
