# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0047_auto_20180109_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
