# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0048_delete_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimages',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Course'},
        ),
    ]
